-- MySQL Script generated by MySQL Workbench
-- 06/06/16 12:26:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USERS` (
  `idUSERS` INT NOT NULL,
  `nameUser` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `dateUsers` DATETIME NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`idUSERS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOCATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOCATIONS` (
  `idLOCATIONS` INT NOT NULL AUTO_INCREMENT,
  `nameLocations` VARCHAR(45) NOT NULL,
  `lat` VARCHAR(45) NOT NULL,
  `long` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLOCATIONS`),
  UNIQUE INDEX `coords_UNIQUE` (`lat` ASC),
  UNIQUE INDEX `long_UNIQUE` (`long` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MUSICS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MUSICS` (
  `idmusics` INT NOT NULL AUTO_INCREMENT,
  `ref` VARCHAR(45) NULL,
  `nameMusics` VARCHAR(45) NULL,
  `artist` VARCHAR(45) NULL,
  `album` VARCHAR(45) NULL,
  `linkMusics` VARCHAR(45) NULL,
  `dateMusics` DATETIME NULL,
  PRIMARY KEY (`idmusics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`POSTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`POSTS` (
  `idPOSTS` INT NOT NULL AUTO_INCREMENT,
  `linkPosts` VARCHAR(45) NULL,
  `datePosts` DATETIME NOT NULL,
  `decaWeb` TINYINT(1) NULL,
  `USERS_idUSERS` INT NOT NULL,
  `LOCATIONS_idLOCATIONS` INT NOT NULL,
  `MUSICS_idmusics` INT NOT NULL,
  PRIMARY KEY (`idPOSTS`),
  INDEX `fk_POSTS_USERS_idx` (`USERS_idUSERS` ASC),
  INDEX `fk_POSTS_LOCATIONS1_idx` (`LOCATIONS_idLOCATIONS` ASC),
  INDEX `fk_POSTS_MUSICS1_idx` (`MUSICS_idmusics` ASC),
  CONSTRAINT `fk_POSTS_USERS`
    FOREIGN KEY (`USERS_idUSERS`)
    REFERENCES `mydb`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POSTS_LOCATIONS1`
    FOREIGN KEY (`LOCATIONS_idLOCATIONS`)
    REFERENCES `mydb`.`LOCATIONS` (`idLOCATIONS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POSTS_MUSICS1`
    FOREIGN KEY (`MUSICS_idmusics`)
    REFERENCES `mydb`.`MUSICS` (`idmusics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REPORT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REPORT` (
  `idREPORT` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `dateReport` DATETIME NOT NULL,
  `USERS_idUSERS` INT NOT NULL,
  `POSTS_idPOSTS` INT NOT NULL,
  PRIMARY KEY (`idREPORT`),
  INDEX `fk_REPORT_USERS1_idx` (`USERS_idUSERS` ASC),
  INDEX `fk_REPORT_POSTS1_idx` (`POSTS_idPOSTS` ASC),
  CONSTRAINT `fk_REPORT_USERS1`
    FOREIGN KEY (`USERS_idUSERS`)
    REFERENCES `mydb`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REPORT_POSTS1`
    FOREIGN KEY (`POSTS_idPOSTS`)
    REFERENCES `mydb`.`POSTS` (`idPOSTS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PLAYLISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PLAYLISTS` (
  `idPLAYLISTS` INT NOT NULL AUTO_INCREMENT,
  `namePlaylists` VARCHAR(45) NULL,
  `datePlaylists` DATETIME NULL,
  PRIMARY KEY (`idPLAYLISTS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUBSCRIPTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SUBSCRIPTIONS` (
  `USERS_idUSERS` INT NULL,
  `USERS_idUSERS1` INT NULL,
  `PLAYLISTS_idPLAYLISTS` INT NULL,
  PRIMARY KEY (`USERS_idUSERS`, `USERS_idUSERS1`, `PLAYLISTS_idPLAYLISTS`),
  INDEX `fk_USERS_has_USERS_USERS2_idx` (`USERS_idUSERS1` ASC),
  INDEX `fk_USERS_has_USERS_USERS1_idx` (`USERS_idUSERS` ASC),
  INDEX `fk_SUBSCRIPTIONS_PLAYLISTS1_idx` (`PLAYLISTS_idPLAYLISTS` ASC),
  CONSTRAINT `fk_USERS_has_USERS_USERS1`
    FOREIGN KEY (`USERS_idUSERS`)
    REFERENCES `mydb`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_has_USERS_USERS2`
    FOREIGN KEY (`USERS_idUSERS1`)
    REFERENCES `mydb`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUBSCRIPTIONS_PLAYLISTS1`
    FOREIGN KEY (`PLAYLISTS_idPLAYLISTS`)
    REFERENCES `mydb`.`PLAYLISTS` (`idPLAYLISTS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USERS_has_PLAYLISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USERS_has_PLAYLISTS` (
  `USERS_idUSERS` INT NULL,
  `PLAYLISTS_idPLAYLISTS` INT NULL,
  PRIMARY KEY (`PLAYLISTS_idPLAYLISTS`, `USERS_idUSERS`),
  INDEX `fk_USERS_has_PLAYLISTS_PLAYLISTS1_idx` (`PLAYLISTS_idPLAYLISTS` ASC),
  INDEX `fk_USERS_has_PLAYLISTS_USERS1_idx` (`USERS_idUSERS` ASC),
  CONSTRAINT `fk_USERS_has_PLAYLISTS_USERS1`
    FOREIGN KEY (`USERS_idUSERS`)
    REFERENCES `mydb`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_has_PLAYLISTS_PLAYLISTS1`
    FOREIGN KEY (`PLAYLISTS_idPLAYLISTS`)
    REFERENCES `mydb`.`PLAYLISTS` (`idPLAYLISTS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MUSICS_has_PLAYLISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MUSICS_has_PLAYLISTS` (
  `MUSICS_idmusics` INT NOT NULL,
  `PLAYLISTS_idPLAYLISTS` INT NOT NULL,
  PRIMARY KEY (`MUSICS_idmusics`, `PLAYLISTS_idPLAYLISTS`),
  INDEX `fk_MUSICS_has_PLAYLISTS_PLAYLISTS1_idx` (`PLAYLISTS_idPLAYLISTS` ASC),
  INDEX `fk_MUSICS_has_PLAYLISTS_MUSICS1_idx` (`MUSICS_idmusics` ASC),
  CONSTRAINT `fk_MUSICS_has_PLAYLISTS_MUSICS1`
    FOREIGN KEY (`MUSICS_idmusics`)
    REFERENCES `mydb`.`MUSICS` (`idmusics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MUSICS_has_PLAYLISTS_PLAYLISTS1`
    FOREIGN KEY (`PLAYLISTS_idPLAYLISTS`)
    REFERENCES `mydb`.`PLAYLISTS` (`idPLAYLISTS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MUSICS_has_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MUSICS_has_USERS` (
  `MUSICS_idmusics` INT NOT NULL,
  `USERS_idUSERS` INT NOT NULL,
  PRIMARY KEY (`MUSICS_idmusics`, `USERS_idUSERS`),
  INDEX `fk_MUSICS_has_USERS_USERS1_idx` (`USERS_idUSERS` ASC),
  INDEX `fk_MUSICS_has_USERS_MUSICS1_idx` (`MUSICS_idmusics` ASC),
  CONSTRAINT `fk_MUSICS_has_USERS_MUSICS1`
    FOREIGN KEY (`MUSICS_idmusics`)
    REFERENCES `mydb`.`MUSICS` (`idmusics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MUSICS_has_USERS_USERS1`
    FOREIGN KEY (`USERS_idUSERS`)
    REFERENCES `mydb`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
